export const THEMES: string[] = [
  // 826 categories from notion archive
  "Short Stories",
  "Healthy Foods",
  "Recipes",
  "Creative Writing",
  "Transportation",
  "Cultural Myths",
  "Culture",
  "Food",
  "Diaries",
  "Identity",
  "College Essay",
  "Horror",
  "Superheroes",
  "Manhood",
  "Music",
  "Texting",
  "Aliens",
  "Dreams",
  "Nightmares",
  "Mystery",
  "Oppression",
  "Power",
  "Overcoming",
  "Neighborhood",
  "Informational",
  "Work/Career",
  "Dystopia/Utopia",
  "Bedtime Stories",
  "Gentrification",
  "Climate Change",
  "gifts",
  "The Future",
  "Epiphany",
  "Adventure",
  "Freedom of Expression",
  "Hopes",
  "School",
  "Connections",
  "Marine Conservation",
  "Time Travel",
  "Journal",
  "Bullying",
  "Kindness",
  "Inclusion",
  "Family",
  "Spooky Stories",
  "Camp Cryptid",
  "Leadership",
  "Create Your Own Adventure",
  "Magic",
  "Field Trip",
  "Marginalization",
  "Health and Wellness",
  "City",
  "Policing and Gun Violence",
  "Environment",
  "Coming of Age",
  "Youth",
  "Self-Love",
  "animals",
  "art",
  "passion",
  "weather",
  "Relationships",
  "Belonging",
  "Defiance",
  "Sorrow",
  "immigration",
  "tradition",
  "goals",
];

export interface OmchaiRole {
  key: "owner" | "manager" | "consulted" | "helper" | "approver" | "informed";
  label: string;
}

export const OMCHAI_ROLES: OmchaiRole[] = [
  { key: "owner",     label: "Owner" },
  { key: "manager",   label: "Manager" },
  { key: "consulted", label: "Consulted" },
  { key: "helper",    label: "Helper" },
  { key: "approver",  label: "Approver" },
  { key: "informed",  label: "Informed" },
];