AWSTemplateFormatVersion: "2010-09-09"
Description: Recreated S3 bucket from existing bhchp-bucket configuration

Parameters:
  Name:
    Type: String
    Default: bhchp-bucket

Resources:
  BhchpBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref Name
      VersioningConfiguration:
        Status: Suspended
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
  BhchpBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BhchpBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${BhchpBucket}/*"

Outputs:
  BucketName:
    Value: !Ref BhchpBucket