AWSTemplateFormatVersion: "2010-09-09"
Description: Cognito user pool and clients for proj-bhchp

Parameters:
  CognitoRegion:
    Type: String
    Default: us-east-2
  UserPoolName:
    Type: String
    Default: bhchp-user-pool
  FrontendClientName:
    Type: String
    Default: bhchp-frontend-no-secret
  FrontendRefreshTokenValidityDays:
    Type: Number
    Default: 30
    MinValue: 1
    MaxValue: 3650

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref UserPoolName
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
          - Name: verified_phone_number
            Priority: 2
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      AutoVerifiedAttributes:
        - email
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      MfaConfiguration: "OFF"
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 7
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE

  FrontendUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Ref FrontendClientName
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
      AccessTokenValidity: 60
      IdTokenValidity: 60
      RefreshTokenValidity: !Ref FrontendRefreshTokenValidityDays
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days

Outputs:
  CognitoUserPoolId:
    Value: !Ref UserPool
  ViteCognitoAppClientId:
    Value: !Ref FrontendUserPoolClient
  CognitoRegion:
    Value: !Ref CognitoRegion
