import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
} from 'typeorm';
import { Site } from './types';

/**
 * Represents the desired columns for the database table
 * in the repository for the system's admins
 */
@Entity('admins')
export class Admin {
  /**
   * Autogenerated admin id
   */
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * Name of the admin
   *
   * Example: 'Jane Doe'
   */
  @Column()
  name: string;

  /**
   * Email of the admin
   *
   * Example: 'jane.doe@northeastern.edu'
   */
  @Column({ unique: true })
  email: string;

  /**
   * Site for which the person is an administrator of
   */
  @Column({
    type: 'enum',
    enum: Site,
  })
  site: Site;

  /**
   * When the admin was created stored in YYYY-MM-DD format
   *
   * Example: new Date('2025-01-30')
   */
  @CreateDateColumn({ type: 'timestamp' })
  createdAt: Date;

  /**
   * When the admin was last logged as updated stored in YYYY-MM-DD format
   *
   * Example: new Date('2025-01-30')
   */
  @UpdateDateColumn({ type: 'timestamp' })
  updatedAt: Date;
}
