import { Entity, Column, ObjectIdColumn, ObjectId } from 'typeorm';

import type { Status } from './types';

/**
 * Represents the desired columns for the database table
 * in the repository for the system's users.
 */
@Entity()
export class User {
  /**
   * Autogenerated id of the user.
   */
  @Column({ primary: true })
  id: number;

  /**
   * Status or level of the user, currently either standard or admin.
   *
   * Example: Status.Admin.
   */
  @Column()
  status: Status;

  /**
   * First name of the user.
   *
   * Example: 'Jane'.
   */
  @Column()
  firstName: string;

  /**
   * Last name of the user.
   *
   * Example: 'Doe'.
   */
  @Column()
  lastName: string;

  /**
   * Email of the user.
   *
   * Example: 'jane.doe@northeastern.edu'.
   */
  @Column()
  email: string;
}
