import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

import {
  AppStatus,
  ExperienceType,
  InterestArea,
  School,
  DaysOfTheWeek,
  ApplicantType,
} from './types';
import { DISCIPLINE_VALUES } from '../disciplines/disciplines.constants';

/**
 * Represents the desired columns for the database table in the repository for the system's applications.
 */
@Entity('application')
export class Application {
  /**
   * Autogenerated application id number.
   */
  @PrimaryGeneratedColumn()
  appId!: number;

  /**
   * Email of the applicant.
   *
   * Example: "bob.ross@example.com"
   */
  @Column({ type: 'varchar' })
  email!: string;

  /**
   * Discipline associated with the applicant.
   *
   * Example: "Nursing"
   */
  @Column({ type: 'enum', enum: DISCIPLINE_VALUES })
  discipline!: DISCIPLINE_VALUES;

  /**
   * Status of the application in the review process.
   *
   * Example: AppStatus.APP_SUBMITTED.
   */
  @Column({ type: 'enum', enum: AppStatus, default: AppStatus.APP_SUBMITTED })
  appStatus!: AppStatus;

  /**
   * Availability of the applicant in terms of days of the week.
   *
   * Example: 'Monday, Tuesday'.
   */
  @Column({ type: 'varchar' })
  daysAvailable!: DaysOfTheWeek[];

  /**
   * Experience type/ level of the applicant, generally in terms of medical experience or degree.
   *
   * Example: ExperienceType.BS.
   */
  @Column({ type: 'enum', enum: ExperienceType })
  experienceType!: ExperienceType;

  // TODO: clarify what format these strings are in and an example of what type of file

  /**
   * Applicant's area of interest for the commitment.
   *
   * Example: InterestArea.NURSING.
   */
  @Column({ type: 'enum', enum: InterestArea })
  interest!: InterestArea;

  // TODO: clarify what format this string is in, and why it's not an array
  // if people can hold multiple licenses in real life
  @Column({ type: 'varchar' })
  license!: string;

  /**
   * Phone number of the applicant in ###-###-#### format.
   *
   * Example: "123-456-7890".
   */
  @Column({ type: 'varchar' })
  phone!: string;

  /**
   * Type of applicant, currently either a learner or a volunteer.
   *
   * Example: ApplicantType.LEARNER.
   */
  @Column({ type: 'enum', enum: ApplicantType })
  applicantType!: ApplicantType;

  /**
   * School of the applicant; includes well-known medical schools or an 'other' option.
   *
   * Example: School.STANFORD_MEDICINE.
   */
  @Column({ type: 'enum', enum: School })
  school!: School;

  /**
   * Whether or not the applicant was referred by someone else.
   *
   * Example: false.
   */
  @Column({ type: 'boolean', default: false, nullable: true })
  referred?: boolean;

  /**
   * The email of the person who referred this applicant, if applicable.
   *
   * Example: jane.doe@example.com.
   */
  @Column({ type: 'varchar', nullable: true })
  referredEmail?: string;

  /**
   * Applicant's desired commitment in hours per week.
   *
   * Example: 20.
   */
  @Column({ type: 'int' })
  weeklyHours!: number;

  /**
   * Application's pronouns
   *
   * Example: they/them
   */
  @Column({ type: 'varchar' })
  pronouns: string;

  /**
   * Applicant's languages spoken other than English
   *
   * Example: some german
   */
  @Column({ type: 'varchar', nullable: true })
  nonEnglishLangs?: string;

  /**
   * Description of the type of experience the applicant is looking for
   *
   * Example: I want to give back to the boston community and learn to talk better with patients
   */
  @Column({ type: 'varchar' })
  desiredExperience: string;

  /**
   * Field for someone to elaborate on their discipline if they chose other for discipline dropdown
   *
   * Example:
   */
  @Column({ type: 'varchar', nullable: true })
  elaborateOtherDiscipline?: string;
}
