import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

import {
  AppStatus,
  ExperienceType,
  InterestArea,
  School,
  ApplicantType,
} from './types';
import { DISCIPLINE_VALUES } from '../disciplines/disciplines.constants';

/**
 * Represents the desired columns for the database table in the repository for the system's applications.
 */
@Entity('application')
export class Application {
  /**
   * Autogenerated application id number.
   */
  @PrimaryGeneratedColumn()
  appId!: number;

  /**
   * Email of the applicant.
   *
   * Example: "bob.ross@example.com"
   */
  @Column({ type: 'varchar' })
  email!: string;

  /**
   * Discipline associated with the applicant.
   *
   * Example: "Nursing"
   */
  @Column({ type: 'enum', enum: DISCIPLINE_VALUES })
  discipline!: DISCIPLINE_VALUES;

  /**
   * Discipline or area of interest description of applicant clicked other
   */
  @Column({ type: 'varchar', nullable: true })
  otherDisciplineDescription?: string;

  /**
   * Status of the application in the review process.
   *
   * Example: AppStatus.APP_SUBMITTED.
   */
  @Column({ type: 'enum', enum: AppStatus, default: AppStatus.APP_SUBMITTED })
  appStatus!: AppStatus;

  /**
   * Applicant's Monday availability as a free text string.
   *
   * Example: 12pm and on every other week
   */
  @Column({ type: 'varchar' })
  mondayAvailability: string;

  /**
   * Applicant's Tuesday availability as a free text string.
   *
   * Example: 12pm and on every other week
   */
  @Column({ type: 'varchar' })
  tuesdayAvailability: string;

  /**
   * Applicant's Wednesday availability as a free text string.
   *
   * Example: 12pm and on every other week
   */
  @Column({ type: 'varchar' })
  wednesdayAvailability: string;

  /**
   * Applicant's Thursday availability as a free text string.
   *
   * Example: 12pm and on every other week
   */
  @Column({ type: 'varchar' })
  thursdayAvailability: string;

  /**
   * Applicant's Friday availability as a free text string.
   *
   * Example: 12pm and on every other week
   */
  @Column({ type: 'varchar' })
  fridayAvailability: string;

  /**
   * Applicant's Saturday availability as a free text string.
   *
   * Example: 12pm and on every other week
   */
  @Column({ type: 'varchar' })
  saturdayAvailability: string;

  /**
   * Experience type/ level of the applicant, generally in terms of medical experience or degree.
   *
   * Example: ExperienceType.BS.
   */
  @Column({ type: 'enum', enum: ExperienceType })
  experienceType!: ExperienceType;

  /**
   * Applicant's area of interest for the commitment.
   *
   * Example: InterestArea.NURSING.
   */
  @Column({ type: 'enum', enum: InterestArea })
  interest!: InterestArea;

  /**
   * Any licenses that the applicant holds
   *
   * Example:  PHYSICIAN LICENSE
   */
  @Column({ type: 'varchar' })
  license!: string;

  /**
   * Phone number of the applicant in ###-###-#### format.
   *
   * Example: "123-456-7890".
   */
  @Column({ type: 'varchar' })
  phone!: string;

  /**
   * Type of applicant, currently either a learner or a volunteer.
   *
   * Example: ApplicantType.LEARNER.
   */
  @Column({ type: 'enum', enum: ApplicantType })
  applicantType!: ApplicantType;

  /**
   * School of the applicant; includes well-known medical schools or an 'other' option.
   *
   * Example: School.STANFORD_MEDICINE.
   */
  @Column({ type: 'enum', enum: School })
  school!: School;

  /**
   * Name of school if chose other
   *
   * Example: Northeastern University
   */
  @Column({ type: 'varchar', nullable: true })
  otherSchool?: string;

  /**
   * Whether or not the applicant was referred by someone else.
   *
   * Example: false.
   */
  @Column({ type: 'boolean', default: false, nullable: true })
  referred?: boolean;

  /**
   * The email of the person who referred this applicant, if applicable.
   *
   * Example: jane.doe@example.com.
   */
  @Column({ type: 'varchar', nullable: true })
  referredEmail?: string;

  /**
   * Applicant's desired commitment in hours per week.
   *
   * Example: 20.
   */
  @Column({ type: 'int' })
  weeklyHours!: number;

  /**
   * Application's pronouns
   *
   * Example: they/them
   */
  @Column({ type: 'varchar' })
  pronouns: string;

  /**
   * Applicant's languages spoken other than English
   *
   * Example: some german
   */
  @Column({ type: 'varchar', nullable: true })
  nonEnglishLangs?: string;

  /**
   * Description of the type of experience the applicant is looking for
   *
   * Example: I want to give back to the boston community and learn to talk better with patients
   */
  @Column({ type: 'varchar' })
  desiredExperience: string;

  /**
   * Field for someone to elaborate on their discipline if they chose other for discipline dropdown
   *
   * Example:
   */
  @Column({ type: 'varchar', nullable: true })
  elaborateOtherDiscipline?: string;

  /**
   * Name of the resume file stored in S3 with its extension
   *
   * Example:  janedoe_resume_2_6_2026.pdf
   *
   * Note: In the code when accessing the files we would prepend the s3 address, e.g.
   * a full link looks like this:
   * https://shelter-link-shelters.s3.us-east-2.amazonaws.com/test_photo.webp
   * But since "https://shelter-link-shelters.s3.us-east-2.amazonaws.com/" would look the same
   * for every single file we can just store the file with its extension e.g. "test_photo.webp"
   */
  @Column({ type: 'varchar' })
  resume: string;

  /**
   * Name of the cover letter file stored in S3 with its extension
   *
   * Example:  jane_doe_coverLetter_2_6_2026.pdf
   *
   * Note: In the code when accessing the files we would prepend the s3 address, e.g.
   * a full link looks like this:
   * https://shelter-link-shelters.s3.us-east-2.amazonaws.com/test_photo.webp
   * But since "https://shelter-link-shelters.s3.us-east-2.amazonaws.com/" would look the same
   * for every single file we can just store the file with its extension e.g. "test_photo.webp"
   */
  @Column({ type: 'varchar' })
  coverLetter: string;

  /**
   * Name of the applicant's emergency contact
   *
   * Example:  Jane Doe
   */
  @Column({ type: 'varchar' })
  emergencyContactName!: string;

  /**
   * Phone number of the applicant's emergency contact
   *
   * Example: 111-111-1111
   */
  @Column({ type: 'varchar' })
  emergencyContactPhone!: string;

  /**
   * Relationship between the applicant and their emergency contact
   *
   * Example: Mother
   */
  @Column({ type: 'varchar' })
  emergencyContactRelationship!: string;
}
