import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

import { AppStatus, ExperienceType, InterestArea, School } from './types';

/**
 * Represents the desired columns for the database table in the repository for the system's applications.
 */
@Entity('application')
export class Application {
  /**
   * Autogenerated application id number.
   */
  @PrimaryGeneratedColumn()
  appId!: number;

  /**
   * Status of the application in the review process.
   *
   * Example: AppStatus.APP_SUBMITTED.
   */
  @Column({ type: 'enum', enum: AppStatus, default: AppStatus.APP_SUBMITTED })
  appStatus!: AppStatus;

  /**
   * Availability of the applicant in terms of days of the week.
   *
   * Example: 'Monday, Tuesday'.
   */
  @Column({ type: 'varchar' })
  daysAvailable!: string;

  /**
   * Experience type/ level of the applicant, generally in terms of medical experience or degree.
   *
   * Example: ExperienceType.BS.
   */
  @Column({ type: 'enum', enum: ExperienceType })
  experienceType!: ExperienceType;

  // TODO: clarify what format these strings are in and an example of what type of file
  @Column('text', { array: true, default: [] })
  fileUploads!: string[];

  /**
   * Applicant's area of interest for the commitment.
   *
   * Example: InterestArea.NURSING.
   */
  @Column({ type: 'enum', enum: InterestArea })
  interest!: InterestArea;

  // TODO: clarify what format this string is in, and why it's not an array
  // if people can hold multiple licenses in real life
  @Column({ type: 'varchar' })
  license!: string;

  /**
   * TODO: clarify what international means exactly in business context.
   *
   * Whether or not the applicant is international.
   *
   * Example: true.
   */
  @Column({ type: 'boolean', default: false })
  isInternational!: boolean;

  /**
   * Whether or not the applicant is a learner (e.g. a student).
   *
   * Example: true.
   */
  @Column({ type: 'boolean', default: false })
  isLearner!: boolean;

  /**
   * Phone number of the applicant in ###-###-#### format.
   *
   * Example: "123-456-7890".
   */
  @Column({ type: 'varchar' })
  phone!: string;

  /**
   * School of the applicant; includes well-known medical schools or an 'other' option.
   *
   * Example: School.STANFORD_MEDICINE.
   */
  @Column({ type: 'enum', enum: School })
  school!: School;

  /**
   * Whether or not the applicant was referred by someone else.
   *
   * Example: false.
   */
  @Column({ type: 'boolean', default: false, nullable: true })
  referred?: boolean;

  /**
   * The email of the person who referred this applicant, if applicable.
   *
   * Example: jane.doe@example.com.
   */
  @Column({ type: 'varchar', nullable: true })
  referredEmail?: string;

  /**
   * Applicant's desired commitment in hours per week.
   *
   * Example: 20.
   */
  @Column({ type: 'int' })
  weeklyHours!: number;
}
