name: Backend build

on:
  push:
    branches: ['main', '101-github-actions-ci-automated-frontend-and-backend-builds']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use NodeJS 24.x
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'yarn'

    - name: Create .env file
      run: |

        echo "AWS_BUCKET_NAME=dummy" >> .env
        echo "AWS_SECRET_ACCESS_KEY=dummy" >> .env
        echo "AWS_ACCESS_KEY_ID=dummy" >> .env
        echo "AWS_REGION=us-east-2" >> .env

    - name: Install Dependencies
      run: yarn install

    - name: Build backend
      run: npx nx build backend