name: Frontend build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use NodeJS 24.x
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'yarn'

    - name: Create .env file
      run: |

        echo "AWS_SECRET_ACCESS_KEY=dummy" >> .env
        echo "AWS_ACCESS_KEY_ID=dummy" >> .env
        echo "AWS_REGION=us-east-2" >> .env

    - name: Install Dependencies
      run: yarn install

    - name: Build frontend
      run: npx nx build frontend
