name: Frontend tests run

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use NodeJS 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'yarn'

      - name: Create .env file
        run: |

          echo "AWS_BUCKET_NAME=dummy" >> .env
          echo "AWS_SECRET_ACCESS_KEY=dummy" >> .env
          echo "AWS_ACCESS_KEY_ID=dummy" >> .env
          echo "AWS_REGION=us-east-2" >> .env

      - name: Install Dependencies
        run: yarn install

      - name: Run frontend tests (Vitest via Nx)
        run: npx nx test frontend
